cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED REPO_ROOT OR NOT DEFINED MATRIX)
  message(FATAL_ERROR "REPO_ROOT and MATRIX are required")
endif()

file(STRINGS "${MATRIX}" rows)
set(expected_header "version\tprofile\tconstruct\tstatus\tprovider\tpositive_witness\tnegative_witness\tstandard\tprovenance\tnotes")
list(LENGTH rows row_count)
if(row_count LESS 2)
  message(FATAL_ERROR "VoiceXML support matrix is empty")
endif()
list(GET rows 0 header)
if(NOT header STREQUAL expected_header)
  message(FATAL_ERROR "VoiceXML support matrix header changed: ${header}")
endif()

function(validate_witness witness row_number kind)
  if(witness STREQUAL "-")
    return()
  endif()
  string(FIND "${witness}" "::" sep)
  if(sep LESS 1)
    message(FATAL_ERROR "row ${row_number}: ${kind} witness must be path::test-label")
  endif()
  string(SUBSTRING "${witness}" 0 ${sep} path)
  math(EXPR label_start "${sep} + 2")
  string(SUBSTRING "${witness}" ${label_start} -1 label)
  if(label STREQUAL "")
    message(FATAL_ERROR "row ${row_number}: empty ${kind} test label")
  endif()
  set(full_path "${REPO_ROOT}/${path}")
  if(NOT EXISTS "${full_path}")
    message(FATAL_ERROR "row ${row_number}: witness file does not exist: ${path}")
  endif()
  file(READ "${full_path}" source)
  string(FIND "${source}" "${label}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "row ${row_number}: witness label not found in ${path}: ${label}")
  endif()
endfunction()

set(index 1)
while(index LESS row_count)
  list(GET rows ${index} row)
  math(EXPR row_number "${index} + 1")
  string(FIND "${row}" ";" semicolon)
  if(NOT semicolon EQUAL -1)
    message(FATAL_ERROR
      "row ${row_number}: semicolons are forbidden in TSV fields")
  endif()
  string(REPLACE "\t" ";" cols "${row}")
  list(LENGTH cols col_count)
  if(NOT col_count EQUAL 10)
    message(FATAL_ERROR "row ${row_number}: expected 10 columns, got ${col_count}: ${row}")
  endif()

  list(GET cols 3 status)
  list(GET cols 5 positive)
  list(GET cols 6 negative)
  list(GET cols 8 provenance)

  if(NOT status STREQUAL "SUPPORTED" AND
     NOT status STREQUAL "UNSUPPORTED" AND
     NOT status STREQUAL "PARTIAL" AND
     NOT status STREQUAL "N/A")
    message(FATAL_ERROR "row ${row_number}: invalid status ${status}")
  endif()

  if(status STREQUAL "SUPPORTED" AND positive STREQUAL "-")
    message(FATAL_ERROR "row ${row_number}: SUPPORTED row requires positive witness")
  endif()
  if((status STREQUAL "UNSUPPORTED" OR status STREQUAL "PARTIAL") AND
     negative STREQUAL "-")
    message(FATAL_ERROR "row ${row_number}: restricted row requires negative witness")
  endif()

  if(NOT provenance STREQUAL "local")
    string(FIND "${provenance}" "upstream:" upstream_prefix)
    if(NOT upstream_prefix EQUAL 0)
      message(FATAL_ERROR "row ${row_number}: invalid provenance ${provenance}")
    endif()
  endif()

  validate_witness("${positive}" ${row_number} "positive")
  validate_witness("${negative}" ${row_number} "negative")
  math(EXPR index "${index} + 1")
endwhile()

message(STATUS "Validated ${row_count} VoiceXML support-matrix lines")
